os: linux
dist: xenial

language: node_js

node_js:
  - 17

install:
    - nvm use 17
    - npm install -g gulp-cli
    - npm install
    - gulp --version
    
script:
    # build kbharkiv
    - gulp build -p kbharkiv
    - mv ./dist ./dist-kbharkiv
    
    # build staging
    - gulp build -p kbharkiv-staging
    - mv ./dist ./dist-kbharkiv-staging

    # build frederiksberg
    - gulp build -p frederiksberg
    - mv ./dist ./dist-frederiksberg

deploy:
    - provider: s3
      access_key_id: ${AWS_ACCESS_KEY}
      secret_access_key: ${AWS_SECRET_ACCESS_KEY}
      bucket: static.kbharkiv.dk
      cache_control: 'no-cache'
      local_dir: dist-kbharkiv
      upload_dir: kildeviser-sdk
      acl: public_read
      region: eu-west-1
      on:
        repo: CopenhagenCityArchives/KildeviserSearchSDK
        branch: master
      edge: true
      cleanup: false
    - provider: s3
      access_key_id: ${AWS_ACCESS_KEY}
      secret_access_key: ${AWS_SECRET_ACCESS_KEY}
      bucket: static.kbharkiv.dk
      cache_control: 'no-cache'
      local_dir: dist-frederiksberg
      upload_dir: kildeviser-sdk-frederiksberg
      acl: public_read
      region: eu-west-1
      on:
        repo: CopenhagenCityArchives/KildeviserSearchSDK
        branch: master
      edge: true
      cleanup: false      
    - provider: s3
      access_key_id: ${AWS_ACCESS_KEY}
      secret_access_key: ${AWS_SECRET_ACCESS_KEY}
      bucket: static.kbharkiv.dk
      cache_control: 'no-cache'
      local_dir: dist-kbharkiv
      upload_dir: kildeviser-staging-sdk
      acl: public_read
      region: eu-west-1
      on:
        repo: CopenhagenCityArchives/KildeviserSearchSDK
        branch: master
      edge: true
      cleanup: false